name: CI
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
        with:
          ref: master

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.64.0"

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo --minify
      
      - name: LOOOOOG
        run: git log

      - name: Azure Blob Upload
        # You may pin to the exact commit or the version.
        uses: tibor19/static-website-deploy@v1
        with:        
          connection-string: ${{ secrets.CONNECTION_STRING }}
          blob-container-name: '$web'
          folder: './public'
